"use strict";

const NOTIFICATION_TYPES = Object.freeze({
  SUPERVISOR_ASSIGNED_STUDENT: "supervisor_assigned_student",
  SUPERVISOR_EXTENDED_STUDENT: "supervisor_extended_student",
  SUPERVISOR_REPLACED_STUDENT: "supervisor_replaced_student",
  SUPERVISION_ASSIGNED_LECTURER: "supervision_assigned_lecturer",
  SUPERVISION_UPDATED_LECTURER: "supervision_updated_lecturer",
  SUPERVISION_ENDED_LECTURER: "supervision_ended_lecturer",
  SEMESTER_TRANSITION_SCHEDULED_STUDENT: "semester_transition_scheduled_student",
  SEMESTER_TRANSITION_SCHEDULED_LECTURER: "semester_transition_scheduled_lecturer",
  EXTENSION_REQUESTED_LECTURER: "extension_requested_lecturer",
  EXTENSION_INFO_LECTURER: "extension_info_lecturer",
  EXTENSION_DECIDED_STUDENT: "extension_decided_student",
  EXTENSION_DECIDED_LECTURER: "extension_decided_lecturer",
  PERINTISAN_GROUP_REVIEW_REQUIRED: "perintisan_group_review_required",
  PENJALURAN_FORM_SUBMITTED_STUDENT: "penjaluran_form_submitted_student",
  PENJALURAN_PATH_REVIEW_LECTURER: "penjaluran_path_review_lecturer",
  PENJALURAN_PATH_DECIDED_STUDENT: "penjaluran_path_decided_student",
  PENJALURAN_FINAL_QUEUE_STUDENT: "penjaluran_final_queue_student",
  PENJALURAN_FINAL_REJECTED_STUDENT: "penjaluran_final_rejected_student",
  CHANGE_PAMIT_REQUESTED_LECTURER: "change_pamit_requested_lecturer",
  CHANGE_PAMIT_DECIDED_STUDENT: "change_pamit_decided_student",
  CHANGE_REGISTRATION_CREATED_STUDENT: "change_registration_created_student",
  CHANGE_PAMIT_INFO_LECTURER: "change_pamit_info_lecturer",
});

const NOTIFICATION_TITLES = Object.freeze({
  [NOTIFICATION_TYPES.SUPERVISOR_ASSIGNED_STUDENT]: "Pembimbing Skripsi Ditetapkan",
  [NOTIFICATION_TYPES.SUPERVISOR_EXTENDED_STUDENT]: "Penetapan Pembimbing Diperpanjang",
  [NOTIFICATION_TYPES.SUPERVISOR_REPLACED_STUDENT]: "Pembimbing Skripsi Diperbarui",
  [NOTIFICATION_TYPES.SUPERVISION_ASSIGNED_LECTURER]: "Mahasiswa Bimbingan Baru",
  [NOTIFICATION_TYPES.SUPERVISION_UPDATED_LECTURER]: "Penugasan Pembimbing Diperbarui",
  [NOTIFICATION_TYPES.SUPERVISION_ENDED_LECTURER]: "Penugasan Pembimbing Berakhir",
  [NOTIFICATION_TYPES.SEMESTER_TRANSITION_SCHEDULED_STUDENT]: "Kelanjutan Semester Dijadwalkan",
  [NOTIFICATION_TYPES.SEMESTER_TRANSITION_SCHEDULED_LECTURER]: "Kelanjutan Bimbingan Dijadwalkan",
  [NOTIFICATION_TYPES.EXTENSION_REQUESTED_LECTURER]: "Keputusan Izin Semester Ketiga",
  [NOTIFICATION_TYPES.EXTENSION_INFO_LECTURER]: "Informasi Izin Semester Ketiga",
  [NOTIFICATION_TYPES.EXTENSION_DECIDED_STUDENT]: "Keputusan Izin Semester Ketiga",
  [NOTIFICATION_TYPES.EXTENSION_DECIDED_LECTURER]: "Status Izin Semester Ketiga",
  [NOTIFICATION_TYPES.PERINTISAN_GROUP_REVIEW_REQUIRED]: "Kelompok Perintisan Perlu Ditinjau",
  [NOTIFICATION_TYPES.PENJALURAN_FORM_SUBMITTED_STUDENT]: "Form Penjaluran Terkirim",
  [NOTIFICATION_TYPES.PENJALURAN_PATH_REVIEW_LECTURER]: "Review Penjaluran Baru",
  [NOTIFICATION_TYPES.PENJALURAN_PATH_DECIDED_STUDENT]: "Keputusan Penanggung Jawab Jalur",
  [NOTIFICATION_TYPES.PENJALURAN_FINAL_QUEUE_STUDENT]: "Menunggu Keputusan Final",
  [NOTIFICATION_TYPES.PENJALURAN_FINAL_REJECTED_STUDENT]: "Penjaluran Ditolak",
  [NOTIFICATION_TYPES.CHANGE_PAMIT_REQUESTED_LECTURER]: "Permohonan Pamit Ulang/Alih Jalur",
  [NOTIFICATION_TYPES.CHANGE_PAMIT_DECIDED_STUDENT]: "Keputusan Pamit Ulang/Alih Jalur",
  [NOTIFICATION_TYPES.CHANGE_REGISTRATION_CREATED_STUDENT]: "Siklus Penjaluran Baru Dibuat",
  [NOTIFICATION_TYPES.CHANGE_PAMIT_INFO_LECTURER]: "Informasi Pamit Mahasiswa Bimbingan",
});

module.exports = { NOTIFICATION_TYPES, NOTIFICATION_TITLES };
